version: 2.1

jobs:
  run-tests:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: "Install yarn dependencies"
          command: "yarn"

      - run:
          name: "Run tests"
          command: "yarn test"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build_test:
    jobs:
      - run-tests
