version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run:
          name: 'System information'
          command: 'node --version'
      - run:
          name: "Install yarn dependencies"
          command: "yarn"
      - run:
          name: "Build the project"
          command: "yarn build"
      - run:
          name: "Run tests"
          command: "yarn test --json --outputFile=test-results.json"
      - store_test_results:
          path: test-results.json
      - store_artifacts:
          path: test-results.json
workflows:
  build_test:
    jobs:
      - run-tests
